---
services:
  app:
    build:
      context: .
      args:
        DEV: true
    image: paunica/recipe-app-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - dev-static-data:/vol/web
    command: /bin/sh -c "/app/init_db.sh"
    environment:
      DB_HOST: db
      DB_NAME: "${DB_NAME:-devdb}"
      DB_USER: "${DB_USER:-devuser}"
      DB_PASSWORD: "${DB_PASSWORD:-changeme}"
      DJANGO_SETTINGS_MODULE: app.settings
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: changeme
    networks:
      - default

volumes:
  dev-db-data:
  dev-static-data:

networks:
  default:
    driver: bridge
