# Generated by Django 3.2.25 on 2024-10-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_recipe"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="prise",
            new_name="price",
        ),
    ]
