# Generated by Django 3.2.25 on 2024-11-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_ingredient"),
    ]

    operations = [
        migrations.DeleteModel(name="Ingredient", ),
    ]
