# Generated by Django 3.2.25 on 2024-12-09 09:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.models.recipe_image_file_path),
        ),
    ]
